---
name: Deploying image into the Azure Container Registry inside the 'test' evironment

on:
  push:
    branches:
      - "test"

jobs:
  deploy:
    uses: ./.github/workflows/deploy_docker_image.yml
    name: Deploy the test environment
    with:
      environment: Deploy the container into the test test environment Azure Container Registry
    secrets: inherit